### PR TITLE
Added Share.js

### PR DESCRIPTION
**Pull request by joshuaogle**
We haven't done a pull request on your repos before, so let me know if you have any questions.

This adds Share.js (https://github.com/carrot/share-button), which wraps up the social sharing icons in a nice little button with a fun animation. I customized it a little to match the blog but it was already pretty close.

Thoughts on placement?

### CODE REVIEW

**Comment by andreweick** [comment]
Hmmm -- no thoughts on placement.   My first thought was the bottom of the post, but it might get lost down there -- Justified left on the 'date' line? 

Is there an email action in there?

**Comment by joshuaogle** [comment]
I thought you'd take a look at the branch before merging but that's okay, I should have included a screenshot ;)

It is at the bottom in the center. I don't think it gets lost, but we can definitely move it if you think it does.

I totally forgot to add in the Email option though, that's an easy tweak.

**Comment by andreweick** [comment]
:-)  lol -- I should have looked at it first -- that made me laugh (I just hit the merge button)

Give me another chance !  (Actually, I'm not sure how I'd look at the branch first -- pull locally?)

**Comment by joshuaogle** [comment]
Oh, no problem. You merged to master, so you can just pull down master locally now. It's usually a good idea to delete branches after you merge them so you don't have a bunch of old branches around.

**Pull request merged**
