### PR TITLE
WIP: Stories layout

### PR DESCRIPTION
**Pull request by joshuaogle**
Related to #3 

This may be a Work-In-Progress, so let's discuss before merging. Includes full-width images and "covers" (full screen post titles).

Screenshots coming up in the comments.

### CODE REVIEW

**Comment by joshuaogle** [comment]
First let's look at the big new covers. Here is a look at how it normally looks, activated by a "cover:" setting in the header data (see example post).
screen shot 2014-02-17 at 11 46 31 pm

You don't have to set a cover though, it will just render like a normal title if you don't:
screen shot 2014-02-17 at 11 46 15 pm

Block quotes appear nicely between images:
screen shot 2014-02-17 at 11 46 41 pm

Paragraphs are boosted a little in font size just so they can compete with all of these bigger photos:
screen shot 2014-02-17 at 11 46 58 pm

**Comment by andreweick** [comment]
Great photo's make everything look good, don't they?

I'll take a look!

**Comment by andreweick** [comment]
@joshuaogle ok, wow, look great, this totally tracking with what I had in mind!

My problem is when I try to render it, it doesn't look any different to me (especially the cover image?)  I took a peak at the code, and it seemed it should have worked, but I can't seem to get it to render correctly for me?

But this is what I was thinking about -- specialized markup to render

**Comment by joshuaogle** [comment]
Hmm. Did you add

```
layout: 'story'
```

to the top of the post?

**Comment by andreweick** [comment]
I must be doing something wrong -- I just checked out your the stories-layout to a local branch, and then was looking at your beautiful-story-layout the waterfall2x image wasn't a cover image, just a normal image
grab

**Comment by joshuaogle** [comment]
Oh no! It's not you. It looks like it's not adding the body classes like it's supposed to. I didn't change anything since taking my screenshots, so not sure what's up but I'll figure it out and push up a fix.

**Comment by joshuaogle** [comment]
I should have noticed the url on your screenshot. That's the index view, and I'm rendering it like the other blog posts there because I assumed they should be consistent with other posts. If you click on the title, it should go into the story layout.

So that's a question I should have asked in my PR message. How do you want those to display on index pages? The examples you gave all had some simplified version of the post (maybe we take the body off and just have the title and date here?)

**Comment by andreweick** [comment]
HA!  I told you it _was_ my fault :+1: 

How do you think it would look if you took off the "header image" on the story?  I suppose you still need the navigation (although now I understand why everyone is using hamburger buttons)

What do you think of having the cover image be full screen? (like the mission focus.com) with a slight parallax in it as it scrolls?

Yup, on the index page, maybe just the "cover image" with the title?  I'm starting to see why you were trying to talk me into simplified index pages all along.

**Comment by joshuaogle** [comment]
I've been thinking about that and may have just come up with a solution. What would you think about having a hamburger icon but having it in the top middle (rather than in a corner). Clicking the icon would slide in the header from the top, like a shade pull. That way we can keep the header tucked away but it's still in the same format as other pages.

I like the full screen covers, and especially like it with parallax. On Mission Focus it's not really "full screen", it's just large enough that it looks like it is on a specific size of desktop. If you resize you'll notice it doesn't adjust. On my site and Brightbit's site it really does respond to the browser window. Most people might not notice, but it's an easy change if that's what you intended.

Index pages are hard. I think the way Medium does it is good (https://medium.com/), The really simple typography also really makes their category pages work (https://medium.com/health-fitness-1), but I wouldn't necessarily try for that yet.

**Comment by joshuaogle** [comment]
I just noticed the layout of Mission Focus borrows heavily from Medium, so you may have already given that part some thought, it just wouldn't have the author information or picture (since it's all you).

**Comment by andreweick** [comment]
sounds good -- I haven't played with the MF site enough, but I do see glitches when I try it on other devices, so yes, those are the things looking to clean up.

Maybe the round pics could be a category / tag indicator (although that might look to samey?)

**Comment by andreweick** [comment]
Any more thought on this?

Also, what size do you think I should be using for the images?  I've been making the photos

```
WIDTHS = [ 320, 480, 768, 900, 640, 960, 1536, 500, 1800 ]
```

Does that sufficiently cover all the sizes needed?

**Comment by joshuaogle** [comment]
I thought some more about the Missionfocus/Medium approach to index pages and I think that would work really well. You could bump up the per_page to 20 or so that way too.

Those sizes definitely cover everything. I usually aim for 1800 wide, which will cover most desktop screens and the ones that are bigger will still get a (slightly) stretched version that should still look nice.

**Pull request closed without merging**
